In [40]:
(sales[["Units_Sold", "Revenue", "Price"]] < 0).sum()

Units_Sold    0
Revenue       0
Price         0
dtype: int64

In [39]:
sales[["Units_Sold", "Revenue", "Price"]].describe()

         Units_Sold       Revenue         Price
count  36550.000000   36550.00000  36550.000000
mean      14.003010   84707.43385   5892.663800
std        8.467305   76534.63044   3138.775609
min        0.000000       0.00000    663.460000
25%        7.000000   27643.70000   3484.090000
50%       13.000000   56125.90000   5649.795000
75%       20.000000  127954.32000   8516.600000
max       56.000000  546977.00000  11642.450000

In [38]:
sales.duplicated().sum()

np.int64(0)

In [37]:
sales.isnull().sum()

Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

In [36]:
sales.describe()

,Date,Units_Sold,Revenue,Price,Promotion
count,36550,36550.000000,36550.00000,36550.000000,36550.000000
mean,2024-12-31 00:00:00,14.003010,84707.43385,5892.663800,0.102599
min,2024-01-01 00:00:00,0.000000,0.00000,663.460000,0.000000
25%,2024-07-01 00:00:00,7.000000,27643.70000,3484.090000,0.000000
50%,2024-12-31 00:00:00,13.000000,56125.90000,5649.795000,0.000000
75%,2025-07-02 00:00:00,20.000000,127954.32000,8516.600000,0.000000
max,2025-12-31 00:00:00,56.000000,546977.00000,11642.450000,1.000000
std,NaN,8.467305,76534.63044,3138.775609,0.303439

In [35]:
sales["Date"].min(), sales["Date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [34]:
sales.dtypes

Date          datetime64[us]
SKU                      str
Units_Sold             int64
Revenue              float64
Price                float64
Promotion              int64
dtype: object

In [33]:
sales.isnull().sum().sum()

np.int64(0)

In [32]:
sales.isnull().sum()

Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

In [31]:
sales["Date"].nunique()

731

In [30]:
sales.groupby("SKU").size().describe()

count     50.0
mean     731.0
std        0.0
min      731.0
25%      731.0
50%      731.0
75%      731.0
max      731.0
dtype: float64

In [29]:
(sales["Units_Sold"] == 0).mean() * 100

np.float64(0.5526675786593707)

In [28]:
(sales["Units_Sold"] == 0).sum()

np.int64(202)

In [27]:
sales["Promotion"].value_counts(normalize=True) * 100

Promotion
0    89.740082
1    10.259918
Name: proportion, dtype: float64

In [26]:
sales["Promotion"].value_counts()

Promotion
0    32800
1     3750
Name: count, dtype: int64

In [25]:
sales.drop(columns=["calculated_revenue"], inplace=True)

In [24]:
sales[["Revenue", "calculated_revenue"]].head()

     Revenue  calculated_revenue
0   18320.25            18320.25
1   57085.35            57085.35
2   40391.15            40391.15
3   34307.85            34307.85
4  113918.64           113918.64

In [22]:
(sales["Price"] < 0).sum()

np.int64(0)

In [21]:
(sales["Revenue"] < 0).sum()

np.int64(0)

In [20]:
(sales["Units_Sold"] < 0).sum()

np.int64(0)

In [16]:
sales.groupby(["Date", "SKU"]).size().value_counts()

1    36550
Name: count, dtype: int64

In [15]:
sales["SKU"].nunique()

50

In [17]:
sales["Promotion"].value_counts()

Promotion
0    32800
1     3750
Name: count, dtype: int64

In [14]:
sales["Date"].max()

Timestamp('2025-12-31 00:00:00')

In [18]:
sales.describe()

,Date,Units_Sold,Revenue,Price,Promotion
count,36550,36550.000000,36550.00000,36550.000000,36550.000000
mean,2024-12-31 00:00:00,14.003010,84707.43385,5892.663800,0.102599
min,2024-01-01 00:00:00,0.000000,0.00000,663.460000,0.000000
25%,2024-07-01 00:00:00,7.000000,27643.70000,3484.090000,0.000000
50%,2024-12-31 00:00:00,13.000000,56125.90000,5649.795000,0.000000
75%,2025-07-02 00:00:00,20.000000,127954.32000,8516.600000,0.000000
max,2025-12-31 00:00:00,56.000000,546977.00000,11642.450000,1.000000
std,NaN,8.467305,76534.63044,3138.775609,0.303439

In [13]:
sales["Date"].min()

Timestamp('2024-01-01 00:00:00')

In [12]:
sales["Date"].dtype

dtype('<M8[us]')

In [11]:
sales["Date"] = pd.to_datetime(sales["Date"])

In [10]:
sales["Date"].dtype

In [9]:
sales.duplicated().sum()

np.int64(0)



The sales dataset was checked for missing values.

In [8]:
sales.isnull().sum()

Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

In [7]:
sales.info

<bound method DataFrame.info of              Date     SKU  Units_Sold    Revenue    Price  Promotion
0      2024-01-01  SKU001           5   18320.25  3664.05          0
1      2024-01-01  SKU002          15   57085.35  3805.69          0
2      2024-01-01  SKU003           5   40391.15  8078.23          0
3      2024-01-01  SKU004           5   34307.85  6861.57          0
4      2024-01-01  SKU005          12  113918.64  9493.22          0
...           ...     ...         ...        ...      ...        ...
36545  2025-12-31  SKU046           5   35877.70  7175.54          0
36546  2025-12-31  SKU047           6   47629.32  7938.22          0
36547  2025-12-31  SKU048           7    9656.85  1379.55          0
36548  2025-12-31  SKU049          16   83573.92  5223.37          0
36549  2025-12-31  SKU050           9    7944.48   882.72          0

[36550 rows x 6 columns]>

In [6]:
sales.columns

Index(['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion'], dtype='str')

In [5]:
sales.shape

(36550, 6)

In [4]:
sales.head()

         Date     SKU  Units_Sold    Revenue    Price  Promotion
0  2024-01-01  SKU001           5   18320.25  3664.05          0
1  2024-01-01  SKU002          15   57085.35  3805.69          0
2  2024-01-01  SKU003           5   40391.15  8078.23          0
3  2024-01-01  SKU004           5   34307.85  6861.57          0
4  2024-01-01  SKU005          12  113918.64  9493.22          0

In [3]:
sales = pd.read_csv("../data/raw/sales_daily.csv")

In [1]:
import pandas as pd

# Project FORESIGHT
## Data Inspection

The objective of this notebook is to understand the structure, quality, and basic characteristics of the project datasets before performing analysis and forecasting.